BloggerBlogBundle_homepage:
    path:     /
    defaults: { _controller: "BloggerBlogBundle:Page:index" }
    requirements:
         methods:  GET

BloggerBlogBundle_about:
    path:   /about
    defaults: { _controller: "BloggerBlogBundle:Page:about" }
    requirements:
         methods:  GET
         
BloggerBlogBundle_contact:
    path:  /contact
    defaults: { _controller: "BloggerBlogBundle:Page:contact" }
    requirements:
        methods:  GET|POST    

BloggerBlogBundle_blog_show:
    path:  /{id}/{slug}
    defaults: { _controller: "BloggerBlogBundle:Blog:show" }
    requirements:
        methods:  GET
        id: \d+

BloggerBlogBundle_blog_create:
    path:  /createblog/{blog_id}
    defaults: { _controller: "BloggerBlogBundle:Blog:create" }
    requirements:
        methods:  POST
        id: \d+
        blog_id: \d+
        
BloggerBlogBundle_comment_create:
    path:  /comment/{blog_id}
    defaults: { _controller: "BloggerBlogBundle:Comment:create" }
    requirements:
        methods:  POST
        blog_id: \d+        

BloggerBlogBundle_user_create:
    path:  /registration
    defaults: { _controller: "BloggerBlogBundle:User:registration" }
    requirements:
        methods:  GET|POST  
        
BloggerBlogBundle_signin:
    path:  /signin
    defaults: { _controller: "BloggerBlogBundle:User:signin" }
    requirements:
        methods:  GET|POST   
        blog_id: \d+